{{- if and .Values.apiSecret.create (not .Values.apiSecret.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-deployer.fullname" . }}-api
  labels:
    {{- include "helm-deployer.labels" . | nindent 4 }}
type: Opaque
stringData:
  HELM_API_SECRET: {{ required "values.apiSecret.value is required when apiSecret.create=true and apiSecret.existingSecretName is empty" .Values.apiSecret.value | quote }}
{{- end }}
